///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CardModel {
/*
{
  "success": true,
  "deck_id": "wgn53mt7agof",
  "remaining": 52,
  "shuffled": true
} 
*/

  bool? success;
  String? deckId;
  int? remaining;
  bool? shuffled;

  CardModel({
    this.success,
    this.deckId,
    this.remaining,
    this.shuffled,
  });
  CardModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    deckId = json['deck_id']?.toString();
    remaining = json['remaining']?.toInt();
    shuffled = json['shuffled'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['deck_id'] = deckId;
    data['remaining'] = remaining;
    data['shuffled'] = shuffled;
    return data;
  }
}
