///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DrawCardModelCardsImages {
/*
{
  "svg": "https://deckofcardsapi.com/static/img/KH.svg",
  "png": "https://deckofcardsapi.com/static/img/KH.png"
} 
*/

  String? svg;
  String? png;

  DrawCardModelCardsImages({
    this.svg,
    this.png,
  });
  DrawCardModelCardsImages.fromJson(Map<String, dynamic> json) {
    svg = json['svg']?.toString();
    png = json['png']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['svg'] = svg;
    data['png'] = png;
    return data;
  }
}

class DrawCardModelCards {
/*
{
  "code": "KH",
  "image": "https://deckofcardsapi.com/static/img/KH.png",
  "images": {
    "svg": "https://deckofcardsapi.com/static/img/KH.svg",
    "png": "https://deckofcardsapi.com/static/img/KH.png"
  },
  "value": "KING",
  "suit": "HEARTS"
} 
*/

  String? code;
  String? image;
  DrawCardModelCardsImages? images;
  String? value;
  String? suit;

  DrawCardModelCards({
    this.code,
    this.image,
    this.images,
    this.value,
    this.suit,
  });
  DrawCardModelCards.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    image = json['image']?.toString();
    images = (json['images'] != null)
        ? DrawCardModelCardsImages.fromJson(json['images'])
        : null;
    value = json['value']?.toString();
    suit = json['suit']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['image'] = image;
    if (images != null) {
      data['images'] = images!.toJson();
    }
    data['value'] = value;
    data['suit'] = suit;
    return data;
  }
}

class DrawCardModel {
/*
{
  "success": true,
  "deck_id": "7z33zmjsy1za",
  "cards": [
    {
      "code": "KH",
      "image": "https://deckofcardsapi.com/static/img/KH.png",
      "images": {
        "svg": "https://deckofcardsapi.com/static/img/KH.svg",
        "png": "https://deckofcardsapi.com/static/img/KH.png"
      },
      "value": "KING",
      "suit": "HEARTS"
    }
  ],
  "remaining": 50
} 
*/

  bool? success;
  String? deckId;
  List<DrawCardModelCards?>? cards;
  int? remaining;

  DrawCardModel({
    this.success,
    this.deckId,
    this.cards,
    this.remaining,
  });
  DrawCardModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    deckId = json['deck_id']?.toString();
    if (json['cards'] != null) {
      final v = json['cards'];
      final arr0 = <DrawCardModelCards>[];
      v.forEach((v) {
        arr0.add(DrawCardModelCards.fromJson(v));
      });
      cards = arr0;
    }
    remaining = json['remaining']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['deck_id'] = deckId;
    if (cards != null) {
      final v = cards;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['cards'] = arr0;
    }
    data['remaining'] = remaining;
    return data;
  }
}
